services:
  - type: web
    name: hanno-blog
    runtime: node
    plan: free
    buildCommand: npm install --prod=false; npm run build
    startCommand: npm run start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
