name = "hanno-blog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[build]
command = "npm run pages:build"
# [vars]
# DATABASE_URL="..."
# RESEND_API_KEY="re_..."